/**
 * Trimmed vendored types from @activepieces/pieces-framework.
 * These match the real framework 1:1 for the fields you are graded on.
 * DO NOT EDIT THIS FILE.
 */

// ---------- outputSchema (Part 1) ----------

export type FieldFormat =
  | 'email'
  | 'url'
  | 'date'
  | 'datetime'
  | 'number'
  | 'boolean'
  | 'image'
  | 'html'
  | 'currency'
  | 'filesize'
  | 'duration';

export type OutputSchemaField = {
  key: string;
  label?: string;
  value?: string;
  format?: FieldFormat;
  description?: string;
  dynamicKey?: boolean;
  /** For dynamicKey maps and listItems arrays: which property of each item to show as its label. */
  labelKey?: string;
  currency?: string;
  children?: OutputSchemaField[];
  listItems?: OutputSchemaField[];
};

export type OutputSchema = {
  fields: OutputSchemaField[];
  /** When the output is a top-level array: template for labelling each item, e.g. `#{number}: {title}`. */
  itemLabel?: string;
};

// ---------- AI actions (Part 2) ----------

export type Audience = 'human' | 'ai' | 'both';

export type AiMetadata = {
  description?: string;
  idempotent?: boolean;
};

export type ActionClassification = 'READ' | 'SEARCH' | 'WRITE' | 'DESTRUCTIVE';

// ---------- step-settings UI (Part 3) ----------

export type PropertyGroupDisplay = 'tabs' | 'section' | 'summary' | 'builder' | 'footer';

export type PropertyGroup = {
  key: string;
  display: PropertyGroupDisplay;
  label?: string;
  description?: string;
  icon?: string;
  /** Prop names (keys of the action's `props` object) that belong to this group. */
  props: string[];
};

// ---------- loose Property / createAction shims ----------
// Loosely typed on purpose: enough for this repo to compile; the fields you are
// graded on (above) are strict. The real framework types are stricter.

export type BasePropertyConfig = {
  displayName: string;
  description?: string;
  required: boolean;
  defaultValue?: unknown;
  /** Moves the field into the collapsible Advanced section. */
  advanced?: boolean;
  width?: 'half' | 'full';
  icon?: string;
  placeholder?: string;
  options?: unknown;
};

export type PieceProperty = BasePropertyConfig & { type: string };

const prop =
  (type: string) =>
  (config: BasePropertyConfig): PieceProperty => ({ ...config, type });

export const Property = {
  ShortText: prop('SHORT_TEXT'),
  LongText: prop('LONG_TEXT'),
  Number: prop('NUMBER'),
  Checkbox: prop('CHECKBOX'),
  DateTime: prop('DATE_TIME'),
  StaticDropdown: prop('STATIC_DROPDOWN'),
};

export type ActionConfig = {
  auth?: unknown;
  name: string;
  displayName: string;
  description: string;
  classification?: ActionClassification;
  audience?: Audience;
  aiMetadata?: AiMetadata;
  props: Record<string, PieceProperty>;
  propertyGroups?: PropertyGroup[];
  outputSchema?: OutputSchema;
  run: (context: any) => Promise<unknown>;
};

export function createAction(config: ActionConfig): ActionConfig {
  return config;
}
