/**
 * Minimal stand-in for @activepieces/pieces-common's httpClient, so the
 * vendored actions run outside the monorepo. DO NOT EDIT THIS FILE.
 */

export enum HttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
}

export enum AuthenticationType {
  BEARER_TOKEN = 'BEARER_TOKEN',
}

export type HttpRequest<B = unknown> = {
  method: HttpMethod;
  url: string;
  body?: B;
  headers?: Record<string, string>;
  queryParams?: Record<string, string>;
  authentication?: { type: AuthenticationType; token: string };
};

export const httpClient = {
  async sendRequest<T>(req: HttpRequest<unknown>): Promise<{ status: number; body: T }> {
    const qs = req.queryParams && Object.keys(req.queryParams).length
      ? '?' + new URLSearchParams(req.queryParams).toString()
      : '';
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
      ...(req.headers ?? {}),
    };
    if (req.authentication?.type === AuthenticationType.BEARER_TOKEN) {
      headers['Authorization'] = `Bearer ${req.authentication.token}`;
    }
    const res = await fetch(req.url + qs, {
      method: req.method,
      headers,
      body: req.body === undefined ? undefined : JSON.stringify(req.body),
    });
    const text = await res.text();
    let body: unknown = text;
    try { body = JSON.parse(text); } catch { /* leave as text */ }
    return { status: res.status, body: body as T };
  },
};
