import { OutputSchema } from '../ap/framework.js';

export const meetingOutputSchema: OutputSchema = {
  fields: [
    { key: 'uuid', label: 'UUID' },
    { key: 'id', label: 'Meeting ID', format: 'number' },
    { key: 'host_id', label: 'Host ID' },
    { key: 'host_email', label: 'Host Email', format: 'email' },
    { key: 'topic', label: 'Topic' },
    { key: 'type', label: 'Meeting Type', format: 'number' },
    { key: 'status', label: 'Status' },
    { key: 'start_time', label: 'Start Time', format: 'datetime' },
    { key: 'duration', label: 'Duration (minutes)', format: 'duration' },
    { key: 'timezone', label: 'Timezone' },
    { key: 'agenda', label: 'Agenda' },
    { key: 'created_at', label: 'Created At', format: 'datetime' },
    { key: 'start_url', label: 'Start URL', format: 'url' },
    { key: 'join_url', label: 'Join URL', format: 'url' },
    { key: 'password', label: 'Password' },
    { key: 'h323_password', label: 'H.323 Password' },
    { key: 'pstn_password', label: 'PSTN Password' },
    { key: 'encrypted_password', label: 'Encrypted Password' },
    { key: 'pre_schedule', label: 'Pre-schedule', format: 'boolean' },
    {
      key: 'settings',
      label: 'Meeting Settings',
      children: [
        { key: 'host_video', label: 'Host Video', format: 'boolean' },
        { key: 'participant_video', label: 'Participant Video', format: 'boolean' },
        { key: 'cn_meeting', label: 'Host Meeting in China', format: 'boolean' },
        { key: 'in_meeting', label: 'Host Meeting in India', format: 'boolean' },
        { key: 'join_before_host', label: 'Join Before Host', format: 'boolean' },
        { key: 'jbh_time', label: 'Join Before Host Time', format: 'number' },
        { key: 'mute_upon_entry', label: 'Mute Upon Entry', format: 'boolean' },
        { key: 'watermark', label: 'Watermark', format: 'boolean' },
        { key: 'use_pmi', label: 'Use Personal Meeting ID', format: 'boolean' },
        { key: 'approval_type', label: 'Approval Type', format: 'number' },
        { key: 'audio', label: 'Audio Type' },
        { key: 'auto_recording', label: 'Auto Recording' },
        { key: 'enforce_login', label: 'Enforce Login', format: 'boolean' },
        { key: 'waiting_room', label: 'Waiting Room', format: 'boolean' },
        { key: 'meeting_authentication', label: 'Meeting Authentication', format: 'boolean' },
        { key: 'encryption_type', label: 'Encryption Type' },
        { key: 'private_meeting', label: 'Private Meeting', format: 'boolean' },
        { key: 'alternative_hosts', label: 'Alternative Hosts' },
        { key: 'alternative_hosts_email_notification', label: 'Alternative Hosts Email Notification', format: 'boolean' },
        { key: 'show_share_button', label: 'Show Share Button', format: 'boolean' },
        { key: 'allow_multiple_devices', label: 'Allow Multiple Devices', format: 'boolean' },
      ],
    },
  ],
};